services:
  - type: web
    name: crypto-lstm-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements-backend.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BINANCE_API_KEY
        value: ""
      - key: BINANCE_API_SECRET
        value: ""
